### ISSUE TITLE
500 error when moving thread

### ISSUE THREAD

**Issue by JTSobie** [CryptonZylog/uetrip#2]
When using the Move Thread button, the dialog functions fine when selecting the new location. After pressing the second Move Thread button to confirm, a 500 error appears and the thread is not moved. 
Perhaps it is due to someone else posting?  I successfully moved a post I was the only poster on.

"500 - I've made a huge mistake
Something went horribly wrong while processing your request.
Please wait while the server tries to find where the admin is to fix it…"

[thread to be moved to Members/other](https://www.uetrip.org/groups/256ba3ad-a29b-497b-8c46-63547fbad901/forums/9ed1f87f-afb9-4277-91bc-5886dc094e33/thread/205be452-831e-494a-adab-269e8f01bd8e)

**Comment by CryptonZylog** [comment]
Received error log:

     System.Data.SqlClient.SqlException: The UPDATE statement conflicted with the REFERENCE constraint "FK_ForumPostRevision_ForumPost". The conflict occurred in database "uetrip_pro", table "Forums.PostRevision".

Looking into database architecture.. the tables referenced have multi-column primary keys.
