### ISSUE TITLE
Single thread (1st of 21) on 3rd page not displaying

### ISSUE THREAD

**Issue by JTSobie** [CryptonZylog/uetrip#4]
I originally thought a thread was deleted. It happened to be the 1st of 21 threads at the time. There is some issue that does not show a third page with the first thread if there are 21 threads.  Once the 22nd thread is created, both the 1st and 2nd threads appear on a 3rd page. If the 22nd thread is deleted, the 3rd page is hidden, and the 1st thread is not shown.
I'm not sure if this is a 21-thread issue only, or perhaps a 11, 31, 41, etc. issue.

**Comment by CryptonZylog** [comment]
I just made a fix to the database and deleted your "push" thread. Can you verify that all threads display correctly in that category?

**Comment by CryptonZylog** [comment]
Running `select COUNT(*) from Forums.Thread where CategoryId = '4fbed3dc-fcab-42a3-9b6f-80f4999809eb'` returns 20 records. Looking at the paging on the website - two pages, with 10 threads listed per paged. Seems like it's fixed.
